### PR TITLE
Moved some endpoints to core for iOS generation

### PR DESCRIPTION
**Pull request by lmlynik**

### CODE REVIEW

**Review by maciejburda — APPROVED** [review]

**Comment by maciejburda** [comment]
LGTM 👍

**Comment by adamsmo** [comment]
@lmlynik  sgould we merge it to `develop` or to `meetup-round-1` ?

**Comment by lmlynik** [comment]
More a question to @maciejburda

**Comment by maciejburda** [comment]
let's merge to `meetup-round-1`

Also nice question raised by @adamsmo 

@lmlynik 

We may have a small problem with `pusher/v5/apns/{deviceId}`
We define baseURL with `v5` already. So the best for us would be:
`pusher/apns/{deviceId}`.

**Review by wenjdu — APPROVED** [review]

**Comment by tharpa** [comment]
Guys, I think the end game should be to have pusher endpoints completely incorporated into the core API; their use will be of course optional and subject to world configuration.  Instead of having a separate `/pusher` endpoint, I would rather have `/v5/devices/{deviceId}/pusher/apns` etc.

**Comment by tharpa** [comment]
I will review the pusher API and its architecture with @lmlynik and @adamsmo tomorrow and this part of the API will probably evolve beyond `0.5` so whatever works now should stay I would say.

**Pull request closed without merging**
